name: publish
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to publish"
        required: true
        default: "v0.0.0"

jobs:
  publish:
    name: Publish
    env:
      PUBLISHER_TOKEN: ${{ secrets.PUB_DEV_TOKEN }} # Setting the environment variable from a secret
    environment: pub.dev # Specify the github actions deployment environment
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Publish test
        run: flutter pub publish --dry-run

      - name: Publish to pub.dev
        run: flutter pub publish --force
        env:
          PUBLISHER_TOKEN: ${{ env.PUBLISHER_TOKEN }}
